#!/bin/sh
#
readonly PGNAME="clotp"
readonly VERSION="0.2"
readonly GPG="/usr/bin/gpg2"
readonly OATHTOOL="/usr/bin/oathtool"
readonly XCLIP="/usr/bin/xclip"
#
confdir="${HOME}/.${PGNAME}"
kid=
uid=
digits=6
timestepsize="30s"
algorithm="SHA1"
digitsparampresent=0
timestepsizeparampresent=0
algorithmparampresent=0
clip=0

function splash {
  cat << SPLASH
                                                           .    .   .. ..@
                                                          ... *.&*@/@&%&#
                CLOTP - Command Line OTP generator      .... (@&&@&,#%&%@%%
                                                      ...&@@&&%&&%%#%%##*#%%.
                                                      ,&#&&&%&&&%%%,##.%#%#.
                                                  ...*&#&&&&&&&%%%%(,,/#*#%((%.
                       ..   ..@@@@@@%          . ..,@&&&&&&&&&%%%%%(/    *//.,(
             .../&&&@#..@&&&&&&&&&&&&&&&&@&&&&&&&@&&&&&&&&&%&%%%%##/.     .. .
           %&%&&%%%##/%&&&&&&&&&&&%%&%&&&&&&&&&&%&&&&&&&&&&%%%&%%#(*.
        .&%#*#(((#((( %%&&&&&%&&&&&%%%%%&&&&&&&%%%%%%%&%&%&&%&&&%#/,
       .&#((***/*/****###%&%%%%#%###%%%%&&%%%%%%%%%%%%%%%%%%%%&%%##%.
     .&%%#(#///////****//(#%%%%%%%%/(#%%%%%%%%%%%%%###%%&%%%%%%#((#(.
  .#/#%%#(((%#**(/#(..   .(//((/(/( .,**///#########(*#%%%%%#(//(/, .
 ./#%%%#((/*./*.%,..     ,. ,/((((*    ,,,*******///*,,#((%#%&&,(((#% .
  ./((#//     ,.*.        *.../((/,                     ..*(%##&&(,/*##&.
   .#*.       ,.,         ,. ,/(//                           .. /%%* .,/(.
    ..                       &*/*/#                          .. %#*   ./*,
                             /((*,.,/(.                      .#%/      .(#.
                               *,*  ..//**.               .*(*/,    .,../,
                               .**/   ..(**                           .  ,
                                ,*#(.   .
                                   .,**
SPLASH
}

function help {
  cat << HELP

CLOTP - Command Line OTP generator - Version ${VERSION}

Usage:

  ${PGNAME} [-i|-n|-g|-h|-v] [options] [service]

Mode:

  -i - Import OTP URL
  -n - Adds a new service
  -g - Generates OTP for service (default)
  -h - Shows this help
  -v - shows version and exits

Common options:

  -c path - config directory (defaults to \${HOME}/.${PGNAME})

  -k id - key ID for encryption
  -u user - user ID for encryption

  -d digits - number of digits
  -s time - time-step duration
  -a algorithm - TOTP variant: SHA1, SHA256 or SHA512

  -p - enable clipboard integration (requires xclip)

HELP
}

# Inspired by https://stackoverflow.com/a/45977232 and https://stackoverflow.com/a/63993578
readonly URI_REGEX='^otpauth://([th]otp)/((([^:]*):)|((.*)%3A))?([^?]*)\?((%20)*)(&?secret=([^&]*)|&?algorithm=([^&]*)|&?digits=([^&]*)|&?counter=([^&]*)|&?period=([^&]*))*$'
#                              ^         ^^^         ^^         ^        ^^      ^         ^                   ^                ^                 ^                ^
#                              1 type    ||4 issuer  |6 issuer  7 user   |9 %20  10 "or"   11 secret           12 algorithm     13 digits         14 counter       15 period
#                                        |3 issuer:  5 issuer%3A         8 %20%20...
#                                        2 issuer: or issuer%3A

function parse_url {
  [[ "$@" =~ ${URI_REGEX} ]] && {
    URL_TYPE="${BASH_REMATCH[1]}"
    URL_ISSUER="${BASH_REMATCH[4]}"
    test -z "${BASH_REMATCH[6]}" || URL_ISSUER="${BASH_REMATCH[6]}"
    URL_USER="${BASH_REMATCH[7]}"
    URL_SECRET="${BASH_REMATCH[11]}"
    URL_ALGORITHM="${BASH_REMATCH[12]}"
    URL_DIGITS="${BASH_REMATCH[13]}"
    URL_COUNTER="${BASH_REMATCH[14]}"
    URL_PERIOD="${BASH_REMATCH[15]}"
  }
  return $?
}

function init {
  test -d "${confdir}" || mkdir "${confdir}"
}

function import {
  echo -n "Please enter OTP URL: "
  read
  parse_url "${REPLY}"
  [ $? -ne 0 ] && return 1
  init
  svc="${URL_ISSUER}/${URL_USER}"
  test -z "${URL_ISSUER}" && svc="${URL_USER}"
  test -d "${confdir}/${svc}" && echo "${PGNAME}: ${svc} already exists in ${confdir}" && return 1
  mkdir -p "${confdir}/${svc}"
  umask 0066
  cat > "${confdir}/${svc}/key" << KEY
${URL_SECRET}
KEY
  ${GPG} -u "${kid}" -r "${uid}" --encrypt "${confdir}/${svc}/key"
  rm "${confdir}/${svc}/key" 
  test -z "${URL_DIGITS}" || echo "digits=${URL_DIGITS}" >> "${confdir}/${svc}/${PGNAME}.conf"
  test -z "${URL_PERIOD}" || echo "timestepsize=${URL_PERIOD}s" >> "${confdir}/${svc}/${PGNAME}.conf"
  test -z "${URL_ALGORITHM}" || echo "algorithm=${URL_ALGORITHM}" >> "${confdir}/${svc}/${PGNAME}.conf"
}

function add {
  svc=$1
  test -z "${svc}" && echo "${PGNAME}: missing service name" && return 1
  test -d "${confdir}/${svc}" && echo "${PGNAME}: ${svc} already exists in ${confdir}" && return 1
  init
  mkdir -p "${confdir}/${svc}"
  echo -n "Please enter secret key: "
  read
  umask 0066
  cat > "${confdir}/${svc}/key" << KEY
${REPLY}
KEY
  ${GPG} -u "${kid}" -r "${uid}" --encrypt "${confdir}/${svc}/key"
  rm "${confdir}/${svc}/key" 
  test "${digitsparampresent}" -eq 1 && echo "digits=${digits}" >> "${confdir}/${svc}/${PGNAME}.conf"
  test "${timestepsizeparampresent}" -eq 1 && echo "timestepsize=${timestepsize}" >> "${confdir}/${svc}/${PGNAME}.conf"
  test "${algorithmparampresent}" -eq 1 && echo "algorithm=${algorithm}" >> "${confdir}/${svc}/${PGNAME}.conf"
}

function generate {
  svc=$1
  test -z "${svc}" && echo "${PGNAME}: missing service name" && return 1
  init
  test -d "${confdir}/${svc}" || ( echo "${PGNAME}: ${svc} does not exist in ${confdir}" && return 1 )
  test -f "${confdir}/${svc}/key.gpg" || ( echo "${PGNAME}: key.gpg does not exist in ${confdir}/${svc}" && return 1 )
  # Source config if any
  test -f "${confdir}/${svc}/${PGNAME}.conf" && . "${confdir}/${svc}/${PGNAME}.conf"
  otp=`"${GPG}" -o - --quiet --decrypt "${confdir}/${svc}/key.gpg" | "${OATHTOOL}" -b -d "${digits}" -s "${timestepsize}" --totp=${algorithm} -`
  if [ ${clip} -eq 1 -a -x "${XCLIP}" ]
  then
    echo -n "${otp}" | "${XCLIP}" -sel clip
  fi
  echo "${otp}"
}

function ask_service {
  echo -n "Please enter service name: "
  read
  SVC="${REPLY}"
}

# Parse options
import=0
add=0
generate=0
help=0
while getopts inghc:k:u:d:pa:v OPT
do
  case "${OPT}"
  in
    (i)
      import=1
      ;;
    (n)
      add=1
      ;;
    (g)
      generate=1
      ;;
    (h)
      help
      exit 1
      ;;
    (c)
      confdir="${OPTARG}"
      ;;
    (k)
      kid="${OPTARG}"
      ;;
    (u)
      uid="${OPTARG}"
      ;;
    (d)
      digits="${OPTARG}"
      digitsparampresent=1
      ;;
    (s)
      timestepsize="${OPTARG}"
      timestepsizeparampresent=1
      ;;
    (p)
      test -x "${XCLIP}" || echo "${PGNAME}: warning: xclip not available, clipboard integration disabled"
      clip=1
      ;;
    (a)
      algorithm="${OPTARG}"
      algorithmparampresent=1
      ;;
    (v)
      echo "${PGNAME} version ${VERSION}"
      exit 0
      ;;
    (*)
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# Warning: -h never gets here!
if [ $(( ${import} + ${add} + ${generate} )) -gt 1 ]
then
  echo "You must choose just one between -i, -n and -g. See ${PGNAME} -h for help."
  exit 1
fi

# Source config if any
test -f "${confdir}/${PGNAME}.conf" && . "${confdir}/${PGNAME}.conf"

if [ ${import} -eq 1 ]
then
  import
  exit 0
fi

if [ ${add} -eq 1 ]
then
  add ${*}
  exit 0
fi

if [ "${BASH_ARGC}" -gt 0 ]
then
  # Assume generate
  generate=1
fi

if [ ${generate} -eq 1 ]
then
  generate ${*}
  exit 0
fi

# We arrive here only if no options were specified
splash
echo
echo -n "Press enter to start: "
read

while true
do
  clear
  echo
  echo "CLOTP v${VERSION} - Main menù"
  echo
  echo "i) import OTP URL"
  echo "n) setup OTP key"
  echo "g) generate OTP"
  echo
  echo "q) quit"
  echo
  echo -n "Enter your choice: "
  read

  case "${REPLY}"
  in
    (i)
      import
      ;;
    (n)
      ask_service
      echo
      add "${SVC}"
      echo
      echo -n "Press enter continue "
      read
      ;;
    (g)
      ask_service
      echo
      generate "${SVC}"
      echo
      echo -n "Press enter continue "
      read
      ;;
    (q)
      exit 0
      ;;
    (*)
      ;;
  esac
done
